/*!
 * toc.js
 * Render a Github-style table of contents in place of the `[TOC]` marker.
 *
 * Kramdown leaves `[TOC]` (written by MWeb/Typora) as a plain paragraph,
 * so we replace it on the client with a nested list built from the headings
 * of the post. Heading ids are generated by kramdown (auto_ids), we only
 * fall back to our own slugger when an id is missing.
 */
(function () {
    'use strict';

    var TOC_MARKER = /^\[{1,2}\s*toc\s*\]{1,2}$/i;
    var HEADINGS = 'h1, h2, h3, h4, h5, h6';
    // Post footer areas living inside `.post-container` must stay out of the TOC.
    var EXCLUDED = '.pager, .related-posts, .share, .comment, .markdown-toc';

    // Github-flavored anchor: lowercased, punctuation dropped, spaces dashed.
    function slugify(text) {
        return text.trim().toLowerCase()
            .replace(/[\s\u3000]+/g, '-')
            .replace(/[!-\/:-@\[-`{-~\u2000-\u206f\u3001-\u303f\uff01-\uff65]/g, '')
            .replace(/^-+|-+$/g, '') || 'section';
    }

    function uniqueId(base, taken) {
        var id = base, i = 1;
        while (taken[id] || document.getElementById(id)) {
            id = base + '-' + i++;
        }
        taken[id] = true;
        return id;
    }

    function findMarkers(container) {
        var markers = [];
        var paragraphs = container.querySelectorAll('p');
        for (var i = 0; i < paragraphs.length; i++) {
            if (TOC_MARKER.test(paragraphs[i].textContent)) markers.push(paragraphs[i]);
        }
        return markers;
    }

    function collectHeadings(container) {
        var nodes = container.querySelectorAll(HEADINGS);
        var headings = [], taken = {};
        for (var i = 0; i < nodes.length; i++) {
            var node = nodes[i];
            if (node.closest && node.closest(EXCLUDED)) continue;
            var text = node.textContent.replace(/\s+/g, ' ').trim();
            if (!text) continue;
            if (!node.id) node.id = uniqueId(slugify(text), taken);
            headings.push({ level: parseInt(node.tagName.charAt(1), 10), text: text, id: node.id });
        }
        return headings;
    }

    // Build nested <ul> from a flat list of headings.
    function buildList(headings) {
        var root = document.createElement('ul');
        var topLevel = Math.min.apply(null, headings.map(function (h) { return h.level; }));
        // Each frame holds the list currently collecting items of `level`.
        var stack = [{ level: topLevel, list: root }];

        headings.forEach(function (heading) {
            while (stack.length > 1 && heading.level < stack[stack.length - 1].level) stack.pop();

            if (heading.level > stack[stack.length - 1].level) {
                var parent = stack[stack.length - 1].list;
                var nested = document.createElement('ul');
                // A skipped level (e.g. h2 -> h4) nests under the previous item.
                (parent.lastChild || parent).appendChild(nested);
                stack.push({ level: heading.level, list: nested });
            }

            var link = document.createElement('a');
            link.href = '#' + heading.id;
            link.textContent = heading.text;

            var item = document.createElement('li');
            item.appendChild(link);
            stack[stack.length - 1].list.appendChild(item);
        });

        return root;
    }

    function buildToc(headings) {
        var toc = document.createElement('div');
        toc.className = 'markdown-toc';

        var title = document.createElement('div');
        title.className = 'markdown-toc-title';
        title.textContent = '目录';

        var toggle = document.createElement('a');
        toggle.className = 'markdown-toc-toggle';
        toggle.href = '#';
        toggle.textContent = '隐藏';
        toggle.addEventListener('click', function (e) {
            e.preventDefault();
            var folded = toc.className.indexOf('fold') !== -1;
            toc.className = folded ? 'markdown-toc' : 'markdown-toc fold';
            toggle.textContent = folded ? '隐藏' : '显示';
        });
        title.appendChild(toggle);

        toc.appendChild(title);
        toc.appendChild(buildList(headings));
        return toc;
    }

    function render() {
        var container = document.querySelector('.post-container') || document.querySelector('article');
        if (!container) return;

        var markers = findMarkers(container);
        if (!markers.length) return;

        var headings = collectHeadings(container);
        markers.forEach(function (marker) {
            if (!headings.length) {
                marker.parentNode.removeChild(marker);
                return;
            }
            marker.parentNode.replaceChild(buildToc(headings), marker);
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', render);
    } else {
        render();
    }
})();
